/**
 * Web App Manifest for ido-bata.
 *
 * Next.js App Router (`src/app/manifest.ts`) compiles this file to
 * `/manifest.webmanifest` at build time and injects the appropriate
 * `<link rel="manifest">` tag into the document head. No manual link
 * management is required in `layout.tsx`.
 *
 * Consumed by:
 *   - PWA install prompts (mobile home screen, browser install)
 *   - Lighthouse PWA audit (manifest presence is one of the installability
 *     requirements)
 *   - Discord / Slack link unfurl (theme_color and background_color are
 *     surfaced as preview chrome)
 *
 * Icon sizes referenced here must exist as actual assets in `src/app/` (or
 * any directory Next.js can statically serve from the build output). The
 * favicon / icon / apple-icon assets are generated by
 * `scripts/gen-icons.ts`; if you change filenames there, mirror them here.
 *
 * Refs:
 *   - docs/release.md
 *   - Issue #28
 */
import type { MetadataRoute } from "next";

/**
 * `output: "export"` requires every Route Handler to be explicitly
 * static-prerenderable. The manifest has no dynamic inputs, so
 * `force-static` is the correct opt-in.
 *
 * Refs:
 *   - https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
 *   - https://nextjs.org/docs/app/guides/static-exports#route-handlers
 */
export const dynamic = "force-static";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "ido-bata",
    short_name: "ido-bata",
    description: "ido-bata organization 公式 Discord コミュニティのポータル",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    // Discord blurple — matches `src/app/icon.png` background.
    background_color: "#5865F2",
    theme_color: "#5865F2",
    lang: "ja",
    dir: "ltr",
    categories: ["social", "community"],
    icons: [
      {
        src: "/favicon.ico",
        sizes: "16x16 32x32 48x48",
        type: "image/x-icon",
        purpose: "any",
      },
      {
        src: "/icon.png",
        sizes: "32x32",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/apple-icon.png",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
