/**
 * Discord server channel definitions.
 *
 * The `/channels` page imports from this file so visitors can see what
 * topics exist before joining. Ordering is the array declaration order;
 * categories preserve their array order.
 *
 * Source of truth: the Discord guild snapshot fetched via the
 * ido-bata-server-bot (see Issue #101). The snapshot is generated by
 * `.tmp/fetch-discord-snapshot.ts` (gitignored) and is NOT consulted
 * at build time — values here are hand-normalised so the public site
 * never depends on a live bot token.
 *
 * Editorial decisions baked into this file (vs. the raw Discord data):
 *   - The Discord guild name "いど端" is preserved in branding copy,
 *     but channel display names follow the on-server strings verbatim.
 *   - "ご案内" is a public-facing umbrella for the top-level welcome
 *     channels (`#ようこそ` / `#この鯖について` / `#自己紹介`).
 *     `#moderator-only` (staff-only) is intentionally excluded.
 *   - Per-channel `description` is the Discord `topic` when present
 *     and the empty string otherwise. We do not invent purposes that
 *     are not stated on the server.
 *   - Channel order inside each category matches Discord's `position`
 *     (top-to-bottom in the server's sidebar).
 */

export type ChannelCategory = string;

export interface Channel {
  /** Discord display name (without the leading `#`). */
  name: string;
  /**
   * Channel purpose / topic. Empty string when Discord's `topic` is
   * unset — we deliberately do not guess at a purpose.
   */
  description: string;
  /** Category the channel belongs to. */
  category: ChannelCategory;
}

/**
 * Display order is controlled by declaration order. Categories appear in the
 * order they are listed here.
 */
export const CHANNEL_CATEGORIES: readonly ChannelCategory[] = [
  "ご案内",
  "いど端 底力 タイム",
  "話題",
  "PDCA",
  "共有",
  "参考",
  "雑",
  "作業",
  "いど端LT会",
  "LayerNote",
  "要望",
  "Legacy",
];

export const CHANNELS: readonly Channel[] = [
  // ───── ご案内 (top-level public welcome channels) ─────
  { name: "ようこそ", description: "", category: "ご案内" },
  { name: "この鯖について", description: "弊ディスコードサーバーの概要", category: "ご案内" },
  { name: "自己紹介", description: "", category: "ご案内" },

  // ───── いど端 底力 タイム ─────
  { name: "いど底-アナウンス", description: "", category: "いど端 底力 タイム" },

  // ───── 話題 ─────
  { name: "映像・アニメーション", description: "", category: "話題" },
  { name: "プログラミング", description: "", category: "話題" },
  { name: "ꓪeb開発・ꓴꓲ", description: "", category: "話題" },
  { name: "ツール開発", description: "", category: "話題" },
  { name: "ゲーム・インタラクション", description: "", category: "話題" },
  { name: "デザイン・イラスト", description: "", category: "話題" },
  { name: "音楽・ꓓꓔꓟ", description: "", category: "話題" },
  { name: "ꓮꓲ", description: "", category: "話題" },
  { name: "技術・工学", description: "科学技術や機械", category: "話題" },
  { name: "文化・社会", description: "", category: "話題" },
  { name: "専門交錯（１）", description: "", category: "話題" },
  { name: "専門交錯（２）", description: "", category: "話題" },

  // ───── PDCA ─────
  { name: "ꓑlan-計画", description: "", category: "PDCA" },
  { name: "ꓓo-実行", description: "", category: "PDCA" },
  { name: "ꓚheck-評価", description: "", category: "PDCA" },
  { name: "ꓮction-改善", description: "", category: "PDCA" },

  // ───── 共有 ─────
  { name: "素材・配布", description: "", category: "共有" },
  { name: "拡張機能・ツール", description: "", category: "共有" },
  { name: "チートシート", description: "", category: "共有" },
  { name: "チュートリアル", description: "", category: "共有" },
  { name: "ブログ・本", description: "", category: "共有" },
  { name: "宣伝・拡散希望", description: "", category: "共有" },
  { name: "募集・告知", description: "", category: "共有" },
  { name: "その他", description: "", category: "共有" },

  // ───── 参考 ─────
  { name: "参考-映像", description: "", category: "参考" },
  { name: "参考-技術", description: "", category: "参考" },
  { name: "参考-表現", description: "", category: "参考" },
  { name: "参考-ꓪeb", description: "", category: "参考" },
  { name: "参考-楽曲", description: "", category: "参考" },
  { name: "参考-その他", description: "", category: "参考" },

  // ───── 雑 ─────
  { name: "雑談", description: "", category: "雑" },
  { name: "wip", description: "", category: "雑" },
  { name: "ひとりごと", description: "", category: "雑" },
  { name: "世迷言", description: "", category: "雑" },

  // ───── 作業 ─────
  { name: "聞き専", description: "", category: "作業" },

  // ───── いど端LT会 ─────
  { name: "アナウンス", description: "", category: "いど端LT会" },
  { name: "テキスト", description: "", category: "いど端LT会" },

  // ───── LayerNote ─────
  { name: "アナウンス", description: "", category: "LayerNote" },
  { name: "テキスト", description: "", category: "LayerNote" },
  { name: "質問", description: "", category: "LayerNote" },

  // ───── 要望 ─────
  { name: "弊鯖", description: "", category: "要望" },
  { name: "メンバー", description: "", category: "要望" },

  // ───── Legacy ─────
  { name: "作業", description: "", category: "Legacy" },
  { name: "作業-宣言", description: "", category: "Legacy" },
  { name: "褒めないwip", description: "", category: "Legacy" },
  { name: "チャット（１）", description: "", category: "Legacy" },
  { name: "チャット（２）", description: "", category: "Legacy" },
  { name: "チャット（３）", description: "", category: "Legacy" },
];